/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Modules;

import com.Database.ConnectionDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author My
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */public String s,s1,s4,s5,s6,s7,sql;
     public int s2,s3;
    public Edit() {
        initComponents();
        
         
    }
    public void setter(String s1,int s2,int s3,String s4,String s5,String s6,String s7)
    { 
    name.setText(s1);
    pres.setText(s2+"");
    pmob.setText(s3+"");
    ad1.setText(s4);
    ad2.setText(s5);
    c.setText(s6);
    st.setText(s7);
    }
    
    public static int e;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edit = new javax.swing.JPanel();
        asd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        b1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        pres = new javax.swing.JTextField();
        pmob = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ad1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ad2 = new javax.swing.JTextArea();
        c = new javax.swing.JTextField();
        st = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel2.setText("edit profile");

        jLabel5.setText("Personal");

        jLabel6.setText("Permanent Address");

        jLabel7.setText("Office Address");

        b1.setText("Change");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        jLabel11.setText("City");

        jLabel12.setText("State");

        ad1.setColumns(20);
        ad1.setRows(5);
        jScrollPane2.setViewportView(ad1);

        ad2.setColumns(20);
        ad2.setRows(5);
        jScrollPane3.setViewportView(ad2);

        st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stActionPerformed(evt);
            }
        });

        jLabel4.setText("Name");

        jLabel15.setText("Phone");

        jLabel16.setText("Residential");

        javax.swing.GroupLayout asdLayout = new javax.swing.GroupLayout(asd);
        asd.setLayout(asdLayout);
        asdLayout.setHorizontalGroup(
            asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(asdLayout.createSequentialGroup()
                .addGroup(asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(asdLayout.createSequentialGroup()
                        .addGroup(asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(asdLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(36, 36, 36)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(asdLayout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel2))
                            .addGroup(asdLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(asdLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15)
                                .addGap(20, 20, 20)
                                .addGroup(asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pmob, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pres, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(asdLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addGroup(asdLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b1)
                                    .addGroup(asdLayout.createSequentialGroup()
                                        .addGroup(asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(33, 33, 33)
                                        .addGroup(asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(st, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(89, 89, 89))))
                            .addGroup(asdLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(asdLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
            .addGroup(asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(asdLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6)
                    .addContainerGap(356, Short.MAX_VALUE)))
        );
        asdLayout.setVerticalGroup(
            asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pmob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(st, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(50, 50, 50)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(b1)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(asdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(asdLayout.createSequentialGroup()
                    .addGap(209, 209, 209)
                    .addComponent(jLabel6)
                    .addContainerGap(462, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout editLayout = new javax.swing.GroupLayout(edit);
        edit.setLayout(editLayout);
        editLayout.setHorizontalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        editLayout.setVerticalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane1.setViewportView(edit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        int flag = 1;
        Connection Database = new ConnectionDB().getConn();
        try{
        
        ResultSet rs = null;
        switch(e)
        {
           case 2:
            s = Customer.nameU;
            PreparedStatement smt1 = Database.prepareStatement("select * from customer where uname = ?");
            smt1.setString(1, s);
            rs = smt1.executeQuery();
            while(rs.next())
            {
            s1=rs.getString(1);
            s2=rs.getInt(2);
            s3=rs.getInt(3);
            s4=rs.getString(4);        
            s5=rs.getString(5);        
            s6=rs.getString(6);       
            s7=rs.getString(7);
            }
            setter(s1,s2,s3,s4,s5,s6,s7);
            sql="insert into customer(name,p_resi,p_per,p_address,o_address,city,state,username,pword) values(?,?,?,?,?,?,?,?,?)";
            break;
            case 3:
            s = Retailer.nameU;
            PreparedStatement smt2 = Database.prepareStatement("select * from retailer where uname = ?");
            smt2.setString(1, s);
            rs = smt2.executeQuery();
            while(rs.next())
            {
            s1=rs.getString(1);
            s2=rs.getInt(2);
            s3=rs.getInt(3);
            s4=rs.getString(4);        
            s5=rs.getString(5);        
            s6=rs.getString(6);       
            s7=rs.getString(7);
            }
            setter(s1,s2,s3,s4,s5,s6,s7);
            sql="insert into retailer(name,p_resi,p_per,p_address,o_address,city,state,username,pword) values(?,?,?,?,?,?,?,?,?)";
            break;
            case 4:
            s = Subloc.nameU;
            PreparedStatement smt3 = Database.prepareStatement("select * from subloc where uname = ?");
            smt3.setString(1, s);
            rs = smt3.executeQuery();
            while(rs.next())
            {
            s1=rs.getString(1);
            s2=rs.getInt(2);
            s3=rs.getInt(3);
            s4=rs.getString(4);        
            s5=rs.getString(5);        
            s6=rs.getString(6);       
            s7=rs.getString(7);
            }
            setter(s1,s2,s3,s4,s5,s6,s7);
            sql="insert into subloc(name,p_resi,p_per,p_address,o_address,city,state,username,pword) values(?,?,?,?,?,?,?,?,?)";
            break;
            case 5:
            s = Supplier.nameU;
            PreparedStatement smt4 = Database.prepareStatement("select * from supplier where uname = ?");
            smt4.setString(1, s);
            rs = smt4.executeQuery();
            while(rs.next())
            {
            s1=rs.getString(1);
            s2=rs.getInt(2);
            s3=rs.getInt(3);
            s4=rs.getString(4);        
            s5=rs.getString(5);        
            s6=rs.getString(6);       
            s7=rs.getString(7);
            }
            setter(s1,s2,s3,s4,s5,s6,s7);
            sql="insert into supplier(name,p_resi,p_per,p_address,o_address,city,state,username,pword) values(?,?,?,?,?,?,?,?,?)";
            break;

        }}catch(Exception e){}
        
        
        if(name.getText().equals("")){JOptionPane.showMessageDialog(rootPane, "Please Enter Name","Information", ERROR_MESSAGE);flag=0;}
        if((pres.getText().equals("")||(pmob.getText().equals("")))){JOptionPane.showMessageDialog(rootPane, "Information", "Please Enter Phone Numbers",ERROR_MESSAGE);flag=0;}
        if(ad1.getText().equals("")){JOptionPane.showMessageDialog(rootPane,  "Please Enter Permanent Address","Information", ERROR_MESSAGE);flag=0;}
        if(ad2.getText().equals("")){JOptionPane.showMessageDialog(rootPane,  "Please Enter Residential Address","Information", ERROR_MESSAGE);flag=0;}
        if(c.getText().equals("")){JOptionPane.showMessageDialog(rootPane,  "Please Enter A City","Information", ERROR_MESSAGE);flag=0;}
        if(st.getText().equals("")){JOptionPane.showMessageDialog(rootPane,  "Please Enter A State","Information", ERROR_MESSAGE);flag=0;}

        if(flag==1)
        {

            try{
                
                PreparedStatement smt=Database.prepareStatement(sql);
                smt.setString(1, name.getText().trim());
                smt.setInt(2, Integer.parseInt(pres.getText()) );
                smt.setInt(3, Integer.parseInt(pmob.getText()) );
                smt.setString(4, ad1.getText().trim());
                smt.setString(5, ad2.getText().trim());
                smt.setString(6,c.getText());
                smt.setString(7,st.getText());
                int a=smt.executeUpdate();
                if(a>0)
                {
                    JOptionPane.showMessageDialog(rootPane,"Value Changed Successfully");
                                        
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"Value Change Failiure!! ");

                }
            }catch(Exception ex){}

        }
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ad1;
    private javax.swing.JTextArea ad2;
    private javax.swing.JPanel asd;
    private javax.swing.JButton b1;
    private javax.swing.JTextField c;
    private javax.swing.JPanel edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pmob;
    private javax.swing.JTextField pres;
    private javax.swing.JTextField st;
    // End of variables declaration//GEN-END:variables
}
